---
- hosts: all
  connection: local
  tags: base
  become: true
  roles:
    - base

  pre_tasks:
    - name: clean repos
      apt:
        autoclean: yes

    - name: update repositories
      apt:
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: workstation
  tags: workstation
  become: true
  roles:
    - workstation

- hosts: miniservers
  tags: miniservers
  become: true
  roles:
    - miniservers
  # tasks:
  #   - include: roles/workstation/tasks/main.yml
  #   - include: tasks/users.yml
  #   - include: tasks/cron.yml
  #   - include: tasks/packages.yml