- name: Check if deluge installed
  stat:
    path: "{{ deluge_path }}"
  register: result_a
  tags: deluge

- name: Check deluge version
  ansible.builtin.command: '{{ deluge_path }} -V'
  register: result_b
  when: "result_a.stat.exists"
  changed_when: False
  failed_when: False
  tags: deluge

- name: Install deluge
  block:

    - name: Add deluge repo
      ansible.builtin.apt_repository:
        repo: 'ppa:deluge-team/stable'
        state: present
        filename: deluge
      tags: deluge

    - name: Install deluge
      apt:
        name: deluge
      tags: deluge

  when: "not result_a.stat.exists or deluge_target_version is not defined or deluge_target_version not in result_b.stdout"
  tags: deluge