# sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose

- name: Check if docker-compose installed
  stat:
    path: "{{ dockercompose_path }}"
  register: result_a
  tags: dockercompose

- name: Check docker-compose version
  ansible.builtin.command: '{{ dockercompose_path }} --version'
  when: "result_a.stat.exists"
  register: result_b
  changed_when: False
  failed_when: False
  tags: dockercompose

- name: Install or upgrade docker-compose if needed
  block:

    - name: Installing docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ dockercompose_target_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
        dest: /tmp

    - name: Installing by moving docker-compose
      ansible.builtin.copy:
        src: /tmp/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
        dest: /usr/bin/docker-compose
        mode: '0755'

    - name: remove docker-compose installer
      ansible.builtin.file:
        path: /tmp/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
        state: absent

  when: "not result_a.stat.exists or dockercompose_target_version is not defined or dockercompose_target_version not in result_b.stdout"
  tags: dockercompose