- name: Check if postman installed
  stat:
    path: "{{ postman_path }}"
  register: result_a
  tags: postman

- name: Check postman version
  ansible.builtin.command: 'snap find postman'
  register: result_b
  when: "result_a.stat.exists"
  changed_when: False
  failed_when: False
  tags: postman

- name: Install obs_studio
  block:

    - name: install postman snap app
      community.general.snap:
        name: postman
      when: ansible_distribution == 'Ubuntu'

  when: "not result_a.stat.exists or postman_target_version is not defined or postman_target_version not in result_b.stdout"
  tags: postman