- name: Check if signal installed
  stat:
    path: "{{ signal_path }}"
  register: result_a
  tags: signal

- name: Check signal version
  ansible.builtin.command: 'snap find signal-desktop'
  register: result_b
  when: "result_a.stat.exists"
  changed_when: False
  failed_when: False
  tags: signal

- name: Install signal
  block:

    - name: install signal snap app
      community.general.snap:
        name: signal-desktop
      when: ansible_distribution == 'Ubuntu'

  when: "not result_a.stat.exists or signal_target_version is not defined or signal_target_version not in result_b.stdout"
  tags: signal