- name: Check if code-insiders installed
  stat:
    path: "{{ codeinsiders_path }}"
  register: result_a
  tags: codeinsiders

- name: Check code insiders version
  ansible.builtin.command: '{{ codeinsiders_path }} --version'
  when: "result_a.stat.exists"
  register: result_b
  changed_when: False
  failed_when: False
  tags: codeinsiders

- name: Install or upgrade vscode if needed
  block:
    - name: Add Microsoft key
      ansible.builtin.apt_key:
        url:  https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add apt source list in a file
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        filename: codeinsiders
        state: present

    - name: Install code-insiders with apt
      apt:
        name: code-insiders
  when: "not result_a.stat.exists or codeinsiders_target_version is not defined or codeinsiders_target_version not in result_b.stdout"
  tags: codeinsiders