- name: Check if zoom installed
  stat:
    path: "{{ zoom_path }}"
  register: result_a
  tags: zoom

- name: Check zoom version
  ansible.builtin.command: 'snap find zoom-client'
  register: result_b
  when: "result_a.stat.exists"
  changed_when: False
  failed_when: False
  tags: zoom

- name: Install zoom
  block:

    - name: install zoom-client snap app
      community.general.snap:
        name: zoom-client
      when: ansible_distribution == 'Ubuntu'

  when: "not result_a.stat.exists or zoom_target_version is not defined or zoom_target_version not in result_b.stdout"
  tags: zoom